# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zailer', '0002_auto_20160622_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='years',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
