# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zailer', '0003_auto_20160622_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('portfolio_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zailer.PortfolioItem')),
                ('name', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zailer.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='project_url',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
