# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zailer', '0004_auto_20160622_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
    ]
