# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zailer', '0006_auto_20160623_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('modification', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('contact', models.CharField(max_length=40)),
                ('img_preview', models.ImageField(upload_to='car_for_sale')),
            ],
        ),
    ]
