# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zailer', '0008_auto_20160623_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='carforsale',
            name='year',
            field=models.IntegerField(default=2012),
            preserve_default=False,
        ),
    ]
